// AUTO-GENERATED by scripts/gen_types.py — DO NOT EDIT

/* tslint:disable */
/* eslint-disable */
/**
/* This file was automatically generated from pydantic models by running pydantic2ts.
/* Do not modify it by hand - just update the pydantic models and then re-run the script
*/

/**
 * 大カテゴリの定義。
 */
export interface CategoryDef {
  id: string;
  name: string;
  keywords?: string[];
  enabled?: boolean;
  order?: number;
}
/**
 * RSS / Qiita / SpeakerDeck ソースの定義。
 */
export interface SourceDef {
  name: string;
  type: "rss" | "qiita" | "speakerdeck";
  url?: string | null;
  params?: {
    [k: string]: unknown;
  } | null;
  enabled?: boolean;
}
/**
 * 配信設定。Cloudflare KV の `settings` キーに永続化される。
 */
export interface UserSettings {
  max_per_category?: number;
  exclude_keywords?: string[];
  include_keywords?: string[];
  sources?: SourceDef[] | null;
  category_defs?: CategoryDef[] | null;
  article_fetch_hours?: number | null;
  gemini_max_input_per_category?: number | null;
}
