"""Pydantic モデル → TypeScript 型定義の自動生成。

出力: dashboard/functions/api/_types.generated.ts
対象: SourceDef, CategoryDef, UserSettings (および依存する Literal 型)
除外: Article, SelectedArticle, ArticleFeedback, UserPreferences
"""

from pathlib import Path

from pydantic2ts import generate_typescript_defs

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "dashboard" / "functions" / "api" / "_types.generated.ts"
JSON2TS = ROOT / "dashboard" / "node_modules" / ".bin" / "json2ts"

EXCLUDE = (
    "Article",
    "SelectedArticle",
    "ArticleFeedback",
    "UserPreferences",
)

HEADER = "// AUTO-GENERATED by scripts/gen_types.py — DO NOT EDIT\n\n"


def main() -> None:
    generate_typescript_defs(
        module="src.core.models",
        output=str(OUT),
        exclude=EXCLUDE,
        json2ts_cmd=str(JSON2TS),
    )
    content = OUT.read_text()
    if not content.startswith("// AUTO-GENERATED"):
        OUT.write_text(HEADER + content)
    print(f"Generated: {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
