name: Rebase Dependabot PRs

on:
  push:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Update branch of open Dependabot PRs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr list \
            --repo "$GITHUB_REPOSITORY" \
            --author "app/dependabot" \
            --state open \
            --json number \
            -q '.[].number' |
          while read -r pr; do
            gh pr update-branch "$pr" \
              --repo "$GITHUB_REPOSITORY"
          done
